---            - name: Setup Node.js environment
  uses: actions/setup-node@v4.3.0
  with:
    # Set always-auth in npmrc.
    always-auth: # optional, default is false
    # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
    node-version: # optional
    # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
    node-version-file: # optional
    # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec.
    check-latest: # optional
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.
    registry-url: # optional
    # Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).
    scope: # optional
    # Used to pull node distributions from node-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
    cache: # optional
    # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
    cache-dependency-path: # optional
          
name: Update dependencies
on:
  schedule:
    - cron:  '* */6 * * *'
  workflow_dispatch:
jobs:
  updatedeps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.21.x"
      env:
        GOARCH: "amd64"

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Install protoc-gen-go
      run: |
        go install github.com/golang/protobuf/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Update deps
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: make update-external-dependencies

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        commit-message: update external dependencies
        title: Update external dependencies
        body: Check for new images, test vectors and proto files and update the code to use them.
        branch: update-external-dependencies
        base: develop
        author: int-bot <int-bot@users.noreply.github.com>
        committer: int-bot <int-bot@users.noreply.github.com>
